REPLY_RANKING = "reply_ranking"
REPLY_RANKING_RECOVERY = "reply_ranking_recovery"
TOPIC_UNIFIED_POSTS_V3 = "content-understanding-realtime-unified-posts-v3"
TOPIC_REPLY_RANKING_RECOVERY = "reply_ranking_annotation_recovery_v2"
GEMMA_2 = "oai-gemma4-26b-2"
